#!/bin/bash
read -p "Enter a path: " path
if [[ -d $path ]];
then
	echo "Files in $path: "
	ls "$path"
else
echo "$path is not a directory. Please, give a correct path of a directory"
read -p "Eneter a path: " path
echo "Files in $path: "
ls "$path"
fi
